version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: turnos
      POSTGRES_PASSWORD: turnos
      POSTGRES_DB: turnos
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://turnos:turnos@db:5432/turnos
      PORT: 4000
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
